ci: add junit report

diff --git a/.github/workflows/pull-request.yaml b/.github/workflows/pull-request.yaml
--- a/.github/workflows/pull-request.yaml
+++ b/.github/workflows/pull-request.yaml
@@ -18,4 +18,10 @@ jobs:
         run: helm dependency update test-helm
       
       - name: Run Helm unit tests
-        run: helm unittest test-helm
+        run: helm unittest test-helm -t JUnit -o reports/test.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/reports/*.xml'
